// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source=job.go -destination=mock/mock_job.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	service "github.com/heptaliane/katarive-server/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockNarrateJobService is a mock of NarrateJobService interface.
type MockNarrateJobService struct {
	ctrl     *gomock.Controller
	recorder *MockNarrateJobServiceMockRecorder
	isgomock struct{}
}

// MockNarrateJobServiceMockRecorder is the mock recorder for MockNarrateJobService.
type MockNarrateJobServiceMockRecorder struct {
	mock *MockNarrateJobService
}

// NewMockNarrateJobService creates a new mock instance.
func NewMockNarrateJobService(ctrl *gomock.Controller) *MockNarrateJobService {
	mock := &MockNarrateJobService{ctrl: ctrl}
	mock.recorder = &MockNarrateJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarrateJobService) EXPECT() *MockNarrateJobServiceMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockNarrateJobService) Enqueue(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockNarrateJobServiceMockRecorder) Enqueue(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockNarrateJobService)(nil).Enqueue), ctx, url)
}

// GetJob mocks base method.
func (m *MockNarrateJobService) GetJob(jobId string) (service.NarrateJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", jobId)
	ret0, _ := ret[0].(service.NarrateJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockNarrateJobServiceMockRecorder) GetJob(jobId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockNarrateJobService)(nil).GetJob), jobId)
}

// MockNarrateJob is a mock of NarrateJob interface.
type MockNarrateJob struct {
	ctrl     *gomock.Controller
	recorder *MockNarrateJobMockRecorder
	isgomock struct{}
}

// MockNarrateJobMockRecorder is the mock recorder for MockNarrateJob.
type MockNarrateJobMockRecorder struct {
	mock *MockNarrateJob
}

// NewMockNarrateJob creates a new mock instance.
func NewMockNarrateJob(ctrl *gomock.Controller) *MockNarrateJob {
	mock := &MockNarrateJob{ctrl: ctrl}
	mock.recorder = &MockNarrateJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarrateJob) EXPECT() *MockNarrateJobMockRecorder {
	return m.recorder
}

// GetResult mocks base method.
func (m *MockNarrateJob) GetResult() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockNarrateJobMockRecorder) GetResult() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockNarrateJob)(nil).GetResult))
}
