// Code generated by MockGen. DO NOT EDIT.
// Source: narrator.go
//
// Generated by this command:
//
//	mockgen -source=narrator.go -destination=mock/mock_narrator.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pluginv1 "github.com/heptaliane/katarive-go-sdk/gen/pb/plugin/v1"
	service "github.com/heptaliane/katarive-server/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockNarratorManager is a mock of NarratorManager interface.
type MockNarratorManager struct {
	ctrl     *gomock.Controller
	recorder *MockNarratorManagerMockRecorder
	isgomock struct{}
}

// MockNarratorManagerMockRecorder is the mock recorder for MockNarratorManager.
type MockNarratorManagerMockRecorder struct {
	mock *MockNarratorManager
}

// NewMockNarratorManager creates a new mock instance.
func NewMockNarratorManager(ctrl *gomock.Controller) *MockNarratorManager {
	mock := &MockNarratorManager{ctrl: ctrl}
	mock.recorder = &MockNarratorManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarratorManager) EXPECT() *MockNarratorManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockNarratorManager) Do(ctx context.Context, basePath, text string, opts ...service.NarrateOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, basePath, text}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockNarratorManagerMockRecorder) Do(ctx, basePath, text any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, basePath, text}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockNarratorManager)(nil).Do), varargs...)
}

// GetName mocks base method.
func (m *MockNarratorManager) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockNarratorManagerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockNarratorManager)(nil).GetName))
}

// Speakers mocks base method.
func (m *MockNarratorManager) Speakers() []*pluginv1.SpeakerInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Speakers")
	ret0, _ := ret[0].([]*pluginv1.SpeakerInfo)
	return ret0
}

// Speakers indicates an expected call of Speakers.
func (mr *MockNarratorManagerMockRecorder) Speakers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Speakers", reflect.TypeOf((*MockNarratorManager)(nil).Speakers))
}

// SupportedOptions mocks base method.
func (m *MockNarratorManager) SupportedOptions() []*pluginv1.NarratorOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedOptions")
	ret0, _ := ret[0].([]*pluginv1.NarratorOption)
	return ret0
}

// SupportedOptions indicates an expected call of SupportedOptions.
func (mr *MockNarratorManagerMockRecorder) SupportedOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedOptions", reflect.TypeOf((*MockNarratorManager)(nil).SupportedOptions))
}

// MockNarratorRegistry is a mock of NarratorRegistry interface.
type MockNarratorRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockNarratorRegistryMockRecorder
	isgomock struct{}
}

// MockNarratorRegistryMockRecorder is the mock recorder for MockNarratorRegistry.
type MockNarratorRegistryMockRecorder struct {
	mock *MockNarratorRegistry
}

// NewMockNarratorRegistry creates a new mock instance.
func NewMockNarratorRegistry(ctrl *gomock.Controller) *MockNarratorRegistry {
	mock := &MockNarratorRegistry{ctrl: ctrl}
	mock.recorder = &MockNarratorRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarratorRegistry) EXPECT() *MockNarratorRegistryMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockNarratorRegistry) Do(ctx context.Context, url, text string, opts ...service.NarrateOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, text}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockNarratorRegistryMockRecorder) Do(ctx, url, text any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, text}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockNarratorRegistry)(nil).Do), varargs...)
}

// Narrators mocks base method.
func (m *MockNarratorRegistry) Narrators() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Narrators")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Narrators indicates an expected call of Narrators.
func (mr *MockNarratorRegistryMockRecorder) Narrators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Narrators", reflect.TypeOf((*MockNarratorRegistry)(nil).Narrators))
}

// Speakers mocks base method.
func (m *MockNarratorRegistry) Speakers() []*service.Speaker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Speakers")
	ret0, _ := ret[0].([]*service.Speaker)
	return ret0
}

// Speakers indicates an expected call of Speakers.
func (mr *MockNarratorRegistryMockRecorder) Speakers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Speakers", reflect.TypeOf((*MockNarratorRegistry)(nil).Speakers))
}

// Use mocks base method.
func (m *MockNarratorRegistry) Use(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Use", name)
}

// Use indicates an expected call of Use.
func (mr *MockNarratorRegistryMockRecorder) Use(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockNarratorRegistry)(nil).Use), name)
}
