// Code generated by MockGen. DO NOT EDIT.
// Source: source.go
//
// Generated by this command:
//
//	mockgen -source=source.go -destination=mock/mock_source.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pluginv1 "github.com/heptaliane/katarive-go-sdk/gen/pb/plugin/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceManager is a mock of SourceManager interface.
type MockSourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockSourceManagerMockRecorder
	isgomock struct{}
}

// MockSourceManagerMockRecorder is the mock recorder for MockSourceManager.
type MockSourceManagerMockRecorder struct {
	mock *MockSourceManager
}

// NewMockSourceManager creates a new mock instance.
func NewMockSourceManager(ctrl *gomock.Controller) *MockSourceManager {
	mock := &MockSourceManager{ctrl: ctrl}
	mock.recorder = &MockSourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceManager) EXPECT() *MockSourceManagerMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockSourceManager) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockSourceManagerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockSourceManager)(nil).GetName))
}

// GetSource mocks base method.
func (m *MockSourceManager) GetSource(ctx context.Context, url string) (*pluginv1.GetSourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSource", ctx, url)
	ret0, _ := ret[0].(*pluginv1.GetSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSource indicates an expected call of GetSource.
func (mr *MockSourceManagerMockRecorder) GetSource(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSource", reflect.TypeOf((*MockSourceManager)(nil).GetSource), ctx, url)
}

// IsSupportedURL mocks base method.
func (m *MockSourceManager) IsSupportedURL(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedURL", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupportedURL indicates an expected call of IsSupportedURL.
func (mr *MockSourceManagerMockRecorder) IsSupportedURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedURL", reflect.TypeOf((*MockSourceManager)(nil).IsSupportedURL), url)
}

// MockSourceRegistry is a mock of SourceRegistry interface.
type MockSourceRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSourceRegistryMockRecorder
	isgomock struct{}
}

// MockSourceRegistryMockRecorder is the mock recorder for MockSourceRegistry.
type MockSourceRegistryMockRecorder struct {
	mock *MockSourceRegistry
}

// NewMockSourceRegistry creates a new mock instance.
func NewMockSourceRegistry(ctrl *gomock.Controller) *MockSourceRegistry {
	mock := &MockSourceRegistry{ctrl: ctrl}
	mock.recorder = &MockSourceRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceRegistry) EXPECT() *MockSourceRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSourceRegistry) Get(ctx context.Context, url string) (*pluginv1.GetSourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, url)
	ret0, _ := ret[0].(*pluginv1.GetSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSourceRegistryMockRecorder) Get(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSourceRegistry)(nil).Get), ctx, url)
}
