// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/mock_interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pluginv1 "github.com/heptaliane/katarive-go-sdk/gen/pb/plugin/v1"
	model "github.com/heptaliane/katarive-server/internal/model"
	source "github.com/heptaliane/katarive-server/internal/service/source"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceManager is a mock of SourceManager interface.
type MockSourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockSourceManagerMockRecorder
	isgomock struct{}
}

// MockSourceManagerMockRecorder is the mock recorder for MockSourceManager.
type MockSourceManagerMockRecorder struct {
	mock *MockSourceManager
}

// NewMockSourceManager creates a new mock instance.
func NewMockSourceManager(ctrl *gomock.Controller) *MockSourceManager {
	mock := &MockSourceManager{ctrl: ctrl}
	mock.recorder = &MockSourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceManager) EXPECT() *MockSourceManagerMockRecorder {
	return m.recorder
}

// GetSourceCollection mocks base method.
func (m *MockSourceManager) GetSourceCollection(ctx context.Context, req *pluginv1.GetSourceCollectionRequest) (*pluginv1.GetSourceCollectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceCollection", ctx, req)
	ret0, _ := ret[0].(*pluginv1.GetSourceCollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSourceCollection indicates an expected call of GetSourceCollection.
func (mr *MockSourceManagerMockRecorder) GetSourceCollection(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceCollection", reflect.TypeOf((*MockSourceManager)(nil).GetSourceCollection), ctx, req)
}

// GetSourceItem mocks base method.
func (m *MockSourceManager) GetSourceItem(ctx context.Context, req *pluginv1.GetSourceItemRequest) (*pluginv1.GetSourceItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceItem", ctx, req)
	ret0, _ := ret[0].(*pluginv1.GetSourceItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSourceItem indicates an expected call of GetSourceItem.
func (mr *MockSourceManagerMockRecorder) GetSourceItem(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceItem", reflect.TypeOf((*MockSourceManager)(nil).GetSourceItem), ctx, req)
}

// IsSupportedCollection mocks base method.
func (m *MockSourceManager) IsSupportedCollection(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedCollection", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupportedCollection indicates an expected call of IsSupportedCollection.
func (mr *MockSourceManagerMockRecorder) IsSupportedCollection(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedCollection", reflect.TypeOf((*MockSourceManager)(nil).IsSupportedCollection), url)
}

// IsSupportedItem mocks base method.
func (m *MockSourceManager) IsSupportedItem(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupportedItem", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupportedItem indicates an expected call of IsSupportedItem.
func (mr *MockSourceManagerMockRecorder) IsSupportedItem(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupportedItem", reflect.TypeOf((*MockSourceManager)(nil).IsSupportedItem), url)
}

// Name mocks base method.
func (m *MockSourceManager) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSourceManagerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSourceManager)(nil).Name))
}

// MockSourceRegistry is a mock of SourceRegistry interface.
type MockSourceRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSourceRegistryMockRecorder
	isgomock struct{}
}

// MockSourceRegistryMockRecorder is the mock recorder for MockSourceRegistry.
type MockSourceRegistryMockRecorder struct {
	mock *MockSourceRegistry
}

// NewMockSourceRegistry creates a new mock instance.
func NewMockSourceRegistry(ctrl *gomock.Controller) *MockSourceRegistry {
	mock := &MockSourceRegistry{ctrl: ctrl}
	mock.recorder = &MockSourceRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceRegistry) EXPECT() *MockSourceRegistryMockRecorder {
	return m.recorder
}

// AddCollection mocks base method.
func (m *MockSourceRegistry) AddCollection(ctx context.Context, collectionUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollection", ctx, collectionUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollection indicates an expected call of AddCollection.
func (mr *MockSourceRegistryMockRecorder) AddCollection(ctx, collectionUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollection", reflect.TypeOf((*MockSourceRegistry)(nil).AddCollection), ctx, collectionUrl)
}

// AddItem mocks base method.
func (m *MockSourceRegistry) AddItem(ctx context.Context, itemUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, itemUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockSourceRegistryMockRecorder) AddItem(ctx, itemUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockSourceRegistry)(nil).AddItem), ctx, itemUrl)
}

// GetCollection mocks base method.
func (m *MockSourceRegistry) GetCollection(collectionUrl string) (*model.SourceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", collectionUrl)
	ret0, _ := ret[0].(*model.SourceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockSourceRegistryMockRecorder) GetCollection(collectionUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockSourceRegistry)(nil).GetCollection), collectionUrl)
}

// GetCollections mocks base method.
func (m *MockSourceRegistry) GetCollections(opts ...source.GetSourceOption) ([]*model.SourceCollection, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollections", varargs...)
	ret0, _ := ret[0].([]*model.SourceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollections indicates an expected call of GetCollections.
func (mr *MockSourceRegistryMockRecorder) GetCollections(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollections", reflect.TypeOf((*MockSourceRegistry)(nil).GetCollections), opts...)
}

// GetItem mocks base method.
func (m *MockSourceRegistry) GetItem(itemUrl string) (*model.SourceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", itemUrl)
	ret0, _ := ret[0].(*model.SourceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockSourceRegistryMockRecorder) GetItem(itemUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockSourceRegistry)(nil).GetItem), itemUrl)
}

// GetItems mocks base method.
func (m *MockSourceRegistry) GetItems(opts ...source.GetSourceOption) ([]*model.SourceSummary, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetItems", varargs...)
	ret0, _ := ret[0].([]*model.SourceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockSourceRegistryMockRecorder) GetItems(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockSourceRegistry)(nil).GetItems), opts...)
}
