// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/mock_interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pluginv1 "github.com/heptaliane/katarive-go-sdk/gen/pb/plugin/v1"
	model "github.com/heptaliane/katarive-server/internal/model"
	source "github.com/heptaliane/katarive-server/internal/service/source"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceManager is a mock of SourceManager interface.
type MockSourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockSourceManagerMockRecorder
	isgomock struct{}
}

// MockSourceManagerMockRecorder is the mock recorder for MockSourceManager.
type MockSourceManagerMockRecorder struct {
	mock *MockSourceManager
}

// NewMockSourceManager creates a new mock instance.
func NewMockSourceManager(ctrl *gomock.Controller) *MockSourceManager {
	mock := &MockSourceManager{ctrl: ctrl}
	mock.recorder = &MockSourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceManager) EXPECT() *MockSourceManagerMockRecorder {
	return m.recorder
}

// GetSourceCollection mocks base method.
func (m *MockSourceManager) GetSourceCollection(ctx context.Context, req *pluginv1.GetSourceCollectionRequest) (*pluginv1.GetSourceCollectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceCollection", ctx, req)
	ret0, _ := ret[0].(*pluginv1.GetSourceCollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSourceCollection indicates an expected call of GetSourceCollection.
func (mr *MockSourceManagerMockRecorder) GetSourceCollection(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceCollection", reflect.TypeOf((*MockSourceManager)(nil).GetSourceCollection), ctx, req)
}

// GetSourceItem mocks base method.
func (m *MockSourceManager) GetSourceItem(ctx context.Context, req *pluginv1.GetSourceItemRequest) (*pluginv1.GetSourceItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceItem", ctx, req)
	ret0, _ := ret[0].(*pluginv1.GetSourceItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSourceItem indicates an expected call of GetSourceItem.
func (mr *MockSourceManagerMockRecorder) GetSourceItem(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceItem", reflect.TypeOf((*MockSourceManager)(nil).GetSourceItem), ctx, req)
}

// IsSupported mocks base method.
func (m *MockSourceManager) IsSupported(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupported", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupported indicates an expected call of IsSupported.
func (mr *MockSourceManagerMockRecorder) IsSupported(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupported", reflect.TypeOf((*MockSourceManager)(nil).IsSupported), url)
}

// Name mocks base method.
func (m *MockSourceManager) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSourceManagerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSourceManager)(nil).Name))
}

// MockSourceRegistry is a mock of SourceRegistry interface.
type MockSourceRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSourceRegistryMockRecorder
	isgomock struct{}
}

// MockSourceRegistryMockRecorder is the mock recorder for MockSourceRegistry.
type MockSourceRegistryMockRecorder struct {
	mock *MockSourceRegistry
}

// NewMockSourceRegistry creates a new mock instance.
func NewMockSourceRegistry(ctrl *gomock.Controller) *MockSourceRegistry {
	mock := &MockSourceRegistry{ctrl: ctrl}
	mock.recorder = &MockSourceRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceRegistry) EXPECT() *MockSourceRegistryMockRecorder {
	return m.recorder
}

// SourceCollection mocks base method.
func (m *MockSourceRegistry) SourceCollection(ctx context.Context, url string, opts ...source.SourceOption) (*model.SourceCollection, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SourceCollection", varargs...)
	ret0, _ := ret[0].(*model.SourceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SourceCollection indicates an expected call of SourceCollection.
func (mr *MockSourceRegistryMockRecorder) SourceCollection(ctx, url any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceCollection", reflect.TypeOf((*MockSourceRegistry)(nil).SourceCollection), varargs...)
}

// SourceItem mocks base method.
func (m *MockSourceRegistry) SourceItem(ctx context.Context, url string, opts ...source.SourceOption) (*model.SourceItem, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SourceItem", varargs...)
	ret0, _ := ret[0].(*model.SourceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SourceItem indicates an expected call of SourceItem.
func (mr *MockSourceRegistryMockRecorder) SourceItem(ctx, url any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceItem", reflect.TypeOf((*MockSourceRegistry)(nil).SourceItem), varargs...)
}

// SourceItems mocks base method.
func (m *MockSourceRegistry) SourceItems(ctx context.Context, url string, opts ...source.SourceOption) ([]*model.SourceSummary, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SourceItems", varargs...)
	ret0, _ := ret[0].([]*model.SourceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SourceItems indicates an expected call of SourceItems.
func (mr *MockSourceRegistryMockRecorder) SourceItems(ctx, url any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceItems", reflect.TypeOf((*MockSourceRegistry)(nil).SourceItems), varargs...)
}
