// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/mock_interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	apiv1 "github.com/heptaliane/katarive-server/gen/pb/api/v1"
	job "github.com/heptaliane/katarive-server/internal/service/job"
	gomock "go.uber.org/mock/gomock"
)

// MockJob is a mock of Job interface.
type MockJob[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockJobMockRecorder[T]
	isgomock struct{}
}

// MockJobMockRecorder is the mock recorder for MockJob.
type MockJobMockRecorder[T any] struct {
	mock *MockJob[T]
}

// NewMockJob creates a new mock instance.
func NewMockJob[T any](ctrl *gomock.Controller) *MockJob[T] {
	mock := &MockJob[T]{ctrl: ctrl}
	mock.recorder = &MockJobMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJob[T]) EXPECT() *MockJobMockRecorder[T] {
	return m.recorder
}

// Error mocks base method.
func (m *MockJob[T]) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockJobMockRecorder[T]) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockJob[T])(nil).Error))
}

// Result mocks base method.
func (m *MockJob[T]) Result() *T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Result")
	ret0, _ := ret[0].(*T)
	return ret0
}

// Result indicates an expected call of Result.
func (mr *MockJobMockRecorder[T]) Result() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Result", reflect.TypeOf((*MockJob[T])(nil).Result))
}

// Status mocks base method.
func (m *MockJob[T]) Status() apiv1.JobStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(apiv1.JobStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockJobMockRecorder[T]) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockJob[T])(nil).Status))
}

// MockJobQueue is a mock of JobQueue interface.
type MockJobQueue[S any, T any] struct {
	ctrl     *gomock.Controller
	recorder *MockJobQueueMockRecorder[S, T]
	isgomock struct{}
}

// MockJobQueueMockRecorder is the mock recorder for MockJobQueue.
type MockJobQueueMockRecorder[S any, T any] struct {
	mock *MockJobQueue[S, T]
}

// NewMockJobQueue creates a new mock instance.
func NewMockJobQueue[S any, T any](ctrl *gomock.Controller) *MockJobQueue[S, T] {
	mock := &MockJobQueue[S, T]{ctrl: ctrl}
	mock.recorder = &MockJobQueueMockRecorder[S, T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobQueue[S, T]) EXPECT() *MockJobQueueMockRecorder[S, T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockJobQueue[S, T]) Get(id string) (job.Job[T], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(job.Job[T])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobQueueMockRecorder[S, T]) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobQueue[S, T])(nil).Get), id)
}

// Queue mocks base method.
func (m *MockJobQueue[S, T]) Queue(ctx context.Context, opts ...job.JobOption[S]) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Queue", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Queue indicates an expected call of Queue.
func (mr *MockJobQueueMockRecorder[S, T]) Queue(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queue", reflect.TypeOf((*MockJobQueue[S, T])(nil).Queue), varargs...)
}
