// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/mock_interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	apiv1 "github.com/heptaliane/katarive-server/gen/pb/api/v1"
	job "github.com/heptaliane/katarive-server/internal/service/job"
	gomock "go.uber.org/mock/gomock"
)

// MockJob is a mock of Job interface.
type MockJob struct {
	ctrl     *gomock.Controller
	recorder *MockJobMockRecorder
	isgomock struct{}
}

// MockJobMockRecorder is the mock recorder for MockJob.
type MockJobMockRecorder struct {
	mock *MockJob
}

// NewMockJob creates a new mock instance.
func NewMockJob(ctrl *gomock.Controller) *MockJob {
	mock := &MockJob{ctrl: ctrl}
	mock.recorder = &MockJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJob) EXPECT() *MockJobMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockJob) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockJobMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockJob)(nil).Error))
}

// Status mocks base method.
func (m *MockJob) Status() apiv1.JobStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(apiv1.JobStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockJobMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockJob)(nil).Status))
}

// set mocks base method.
func (m *MockJob) set(status apiv1.JobStatus, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "set", status, err)
}

// set indicates an expected call of set.
func (mr *MockJobMockRecorder) set(status, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "set", reflect.TypeOf((*MockJob)(nil).set), status, err)
}

// MockJobQueue is a mock of JobQueue interface.
type MockJobQueue[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockJobQueueMockRecorder[T]
	isgomock struct{}
}

// MockJobQueueMockRecorder is the mock recorder for MockJobQueue.
type MockJobQueueMockRecorder[T any] struct {
	mock *MockJobQueue[T]
}

// NewMockJobQueue creates a new mock instance.
func NewMockJobQueue[T any](ctrl *gomock.Controller) *MockJobQueue[T] {
	mock := &MockJobQueue[T]{ctrl: ctrl}
	mock.recorder = &MockJobQueueMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobQueue[T]) EXPECT() *MockJobQueueMockRecorder[T] {
	return m.recorder
}

// Queue mocks base method.
func (m *MockJobQueue[T]) Queue(ctx context.Context, opts ...job.JobOption[T]) (job.Job, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Queue", varargs...)
	ret0, _ := ret[0].(job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Queue indicates an expected call of Queue.
func (mr *MockJobQueueMockRecorder[T]) Queue(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queue", reflect.TypeOf((*MockJobQueue[T])(nil).Queue), varargs...)
}
