// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/mock_interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pluginv1 "github.com/heptaliane/katarive-go-sdk/gen/pb/plugin/v1"
	model "github.com/heptaliane/katarive-server/internal/model"
	narrator "github.com/heptaliane/katarive-server/internal/service/narrator"
	gomock "go.uber.org/mock/gomock"
)

// MockNarratorManager is a mock of NarratorManager interface.
type MockNarratorManager struct {
	ctrl     *gomock.Controller
	recorder *MockNarratorManagerMockRecorder
	isgomock struct{}
}

// MockNarratorManagerMockRecorder is the mock recorder for MockNarratorManager.
type MockNarratorManagerMockRecorder struct {
	mock *MockNarratorManager
}

// NewMockNarratorManager creates a new mock instance.
func NewMockNarratorManager(ctrl *gomock.Controller) *MockNarratorManager {
	mock := &MockNarratorManager{ctrl: ctrl}
	mock.recorder = &MockNarratorManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarratorManager) EXPECT() *MockNarratorManagerMockRecorder {
	return m.recorder
}

// Metadata mocks base method.
func (m *MockNarratorManager) Metadata() *model.NarrateManagerMetadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(*model.NarrateManagerMetadata)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockNarratorManagerMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockNarratorManager)(nil).Metadata))
}

// Narrate mocks base method.
func (m *MockNarratorManager) Narrate(ctx context.Context, req *pluginv1.NarrateRequest) (*pluginv1.NarrateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Narrate", ctx, req)
	ret0, _ := ret[0].(*pluginv1.NarrateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Narrate indicates an expected call of Narrate.
func (mr *MockNarratorManagerMockRecorder) Narrate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Narrate", reflect.TypeOf((*MockNarratorManager)(nil).Narrate), ctx, req)
}

// MockNarrateRegistry is a mock of NarrateRegistry interface.
type MockNarrateRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockNarrateRegistryMockRecorder
	isgomock struct{}
}

// MockNarrateRegistryMockRecorder is the mock recorder for MockNarrateRegistry.
type MockNarrateRegistryMockRecorder struct {
	mock *MockNarrateRegistry
}

// NewMockNarrateRegistry creates a new mock instance.
func NewMockNarrateRegistry(ctrl *gomock.Controller) *MockNarrateRegistry {
	mock := &MockNarrateRegistry{ctrl: ctrl}
	mock.recorder = &MockNarrateRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarrateRegistry) EXPECT() *MockNarrateRegistryMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockNarrateRegistry) Do(ctx context.Context, source *model.SourceItem, opts ...narrator.NarrateOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, source}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockNarrateRegistryMockRecorder) Do(ctx, source any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, source}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockNarrateRegistry)(nil).Do), varargs...)
}

// Metadata mocks base method.
func (m *MockNarrateRegistry) Metadata() []*model.NarrateManagerMetadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].([]*model.NarrateManagerMetadata)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockNarrateRegistryMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockNarrateRegistry)(nil).Metadata))
}
